configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-0ebad856a091eb87d02fb1593ea77ab28ba83dcb6b4fb5e44efc9ee140e0f163.yml
openapi_spec_hash: c99ebb352bb1d7823db73ff494635553
config_hash: a220c3ff4a1ce85bc81ef53ce813eb12
