configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-d299c006e7d98bb7c8ef04bd911c3cbfad079dd5562fddf776cad9b4c68ff732.yml
openapi_spec_hash: 870fba9d42aeb621fa9496eafca82f9e
config_hash: f9ef9b88cbed18083bced0c60efd9204
