configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-56f50ed009ccaec89fe6c7e64c44b2138fd3fdc1a67f52553fdf5c0316365149.yml
openapi_spec_hash: 2a51f7bf18f82efd211594c15d07efe9
config_hash: e1dc43ba8af3d2fba43e724419dade1d
