configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-8eadebaafab74685215bc3a6fa24d141c4941adc3b0663f13aa917ba2f5f6414.yml
