configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-e3accd3d0c66f7862523c2ef3b462781e70447c02c3d7e5e0328438968556961.yml
openapi_spec_hash: 4abee6b1cd9caccf62eefd9a654c6c45
config_hash: d5e2babcaddac63ed159f72af6191dc6
