configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-f58744e4827c70e95d79d8f07b08a4390fbdccdc80ed0f7490688e4cc3ec16a7.yml
openapi_spec_hash: 2d5c067ca36fa276ea4959b695bd9e89
config_hash: edeaae5cffb1e45c9e9f1f1cd67144ea
