configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-dad0ac4d55b3d515754fffe1c52b0859b056db1ec0c6e4142da79f6caa7e8f57.yml
openapi_spec_hash: 7e7efcb1746be0f589394f0f424109cf
config_hash: ee470fcadd5ba8aed986aa6abccb7c2c
