configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-9ec1b9ed4b3a9bfeaa85b2d0bd09219faa684a1403e5728f6e2d2b4f275cbd90.yml
openapi_spec_hash: 6ef2f37d9d4b35ba9444c810e322efae
config_hash: a220c3ff4a1ce85bc81ef53ce813eb12
