configured_endpoints: 10
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-9dd121e1c6427f5a6ef3d7a09ec4b64d642dfaee95758a3d14109bc2b2d2cb75.yml
openapi_spec_hash: 25ee956428bfea55ba175fe3bca4bb37
config_hash: fd4a90bb24a00a3fccf53379c34968ff
