configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-98bfe5ac952ea83bd69603d4e826e14a87ea41c87de8c94368d28c0da2b338c4.yml
