configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-c14b79fcb83a6d4943ebc6fbd14fa2e4744b24c5013449cde77057650941800b.yml
openapi_spec_hash: ef899d8f54a4edb81db42cc109f4a406
config_hash: ee470fcadd5ba8aed986aa6abccb7c2c
