configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-9bd80b1bbb5fbfd61879fbe7fdebe10472d37c48454ccbac1548094d4c47e307.yml
openapi_spec_hash: ac72f7402660e1c8bd3654ecc9e5899b
config_hash: 6fe089c26fc2fffa28892aaafb95487f
