configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-50d4a3d70e74d5402c1becb3f2c89296028342ffa3e890aaeabdc89e193a1391.yml
openapi_spec_hash: 64732afdc95ba8ed86b2755fd9bb98e2
config_hash: 5acd5e0b9fd715d23ca9daec2dd70d71
