configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-0d8ab7ff25fe15c46393173205850ef7d635d6605e9829093d4ed767483cea81.yml
