configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-7d83ef2a8afe0ea3a1622df6b20b167bfe07e2996a974f7309abccb9fadef72d.yml
