configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-c506050c53f03f20fd7ff0fd8dddcfaf213c4b1ff7cf6d7ef7a5a3c2f3caab76.yml
openapi_spec_hash: 459e3c6cff817ca732810f2b82b8de42
config_hash: 1fc201274f8ea4501868f70eb8dcada8
