configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-681781df56e5a6cbfdbd63f6faee3f903e3ed23a6e6d2cb5e2f5b89f4da4a2a7.yml
openapi_spec_hash: b1a32dadac87fb2690508a5750977f55
config_hash: a31fec3e293600dd17e128d578ed68cd
