configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/turbopuffer-benesch%2Fturbopuffer-35eba41e89d5abe0254240bcb8c64be40b2f6301dd4ad9be9d1ce357a89fe30e.yml
openapi_spec_hash: 32f0e7772aec8db212f4ce24feb10a97
config_hash: 1fc201274f8ea4501868f70eb8dcada8
