# Code generated by turbopuffer-apigen. DO NOT EDIT.

from typing import Any, Tuple, Union, Literal, Mapping, Sequence, TypedDict

from .rrf_params import RrfParams
from .decay_params import DecayParams
from .embed_params import EmbedParams
from .fuzzy_params import FuzzyParams
from .saturate_params import SaturateParams
from .bm25_clause_params import Bm25ClauseParams
from .contains_any_token_filter_params import ContainsAnyTokenFilterParams
from .contains_all_tokens_filter_params import ContainsAllTokensFilterParams

AggregateBy = Union[Tuple[Literal["Count"]], Tuple[Literal["Sum"], str], Tuple[Literal["Count"], str]]
ExprRefNew = TypedDict("ExprRefNew", {"$ref_new": str})
Expr = Union[ExprRefNew, Tuple[Literal["Embed"], str], Tuple[Literal["Embed"], str, EmbedParams]]
Filter = Union[
    Tuple[str, Literal["Eq"], Any],
    Tuple[str, Literal["NotEq"], Any],
    Tuple[str, Literal["In"], Sequence[Any]],
    Tuple[str, Literal["NotIn"], Sequence[Any]],
    Tuple[str, Literal["Contains"], Any],
    Tuple[str, Literal["NotContains"], Any],
    Tuple[str, Literal["ContainsAny"], Sequence[Any]],
    Tuple[str, Literal["NotContainsAny"], Sequence[Any]],
    Tuple[str, Literal["Lt"], Any],
    Tuple[str, Literal["Lte"], Any],
    Tuple[str, Literal["Gt"], Any],
    Tuple[str, Literal["Gte"], Any],
    Tuple[str, Literal["AnyLt"], Any],
    Tuple[str, Literal["AnyLte"], Any],
    Tuple[str, Literal["AnyGt"], Any],
    Tuple[str, Literal["AnyGte"], Any],
    Tuple[str, Literal["Glob"], str],
    Tuple[str, Literal["NotGlob"], str],
    Tuple[str, Literal["IGlob"], str],
    Tuple[str, Literal["NotIGlob"], str],
    Tuple[str, Literal["Regex"], str],
    Tuple[str, Literal["Fuzzy"], str, FuzzyParams],
    Tuple[str, Literal["ContainsAllTokens"], str],
    Tuple[str, Literal["ContainsAllTokens"], Sequence[str]],
    Tuple[str, Literal["ContainsAllTokens"], str, ContainsAllTokensFilterParams],
    Tuple[str, Literal["ContainsAllTokens"], Sequence[str], ContainsAllTokensFilterParams],
    Tuple[str, Literal["ContainsAnyToken"], str],
    Tuple[str, Literal["ContainsAnyToken"], Sequence[str]],
    Tuple[str, Literal["ContainsAnyToken"], str, ContainsAnyTokenFilterParams],
    Tuple[str, Literal["ContainsAnyToken"], Sequence[str], ContainsAnyTokenFilterParams],
    Tuple[str, Literal["ContainsTokenSequence"], str],
    Tuple[str, Literal["ContainsTokenSequence"], Sequence[str]],
    Tuple[Literal["Not"], "Filter"],
    Tuple[Literal["And"], Sequence["Filter"]],
    Tuple[Literal["Or"], Sequence["Filter"]],
]
GroupByFunction = Tuple[Literal["ForEachUnique"], str]
GroupBy = Union[str, Mapping[str, GroupByFunction]]
RankByAnn = Tuple[str, Literal["ANN"], Sequence[float]]
RankByAnnExpr = Tuple[str, Literal["ANN"], Expr]
RankByKnn = Tuple[str, Literal["kNN"], Sequence[float]]
RankByKnnExpr = Tuple[str, Literal["kNN"], Expr]
RankBySparseKnn = Tuple[str, Literal["SparseKNN"], Mapping[str, float]]
RankByText = Union[
    Tuple[str, Literal["BM25"], str],
    Tuple[str, Literal["BM25"], Sequence[str]],
    Tuple[str, Literal["BM25"], str, Bm25ClauseParams],
    Tuple[str, Literal["BM25"], Sequence[str], Bm25ClauseParams],
    Tuple[Literal["Sum"], Sequence["RankByText"]],
    Tuple[Literal["Max"], Sequence["RankByText"]],
    Tuple[Literal["Product"], float, "RankByText"],
    Tuple[Literal["Product"], "RankByText", float],
    Filter,
    Tuple[Literal["Attribute"], str],
    Tuple[Literal["Saturate"], "RankByText", SaturateParams],
    Tuple[Literal["Decay"], "RankByText", DecayParams],
    Tuple[Literal["Dist"], "RankByText", Any],
]
RankByAttributeOrder = Union[Literal["asc"], Literal["desc"]]
RankByAttribute = Tuple[str, RankByAttributeOrder]
RankByAttributes = Sequence[RankByAttribute]
RankBy = Union[
    RankByAnn,
    RankByAnnExpr,
    RankByKnn,
    RankByKnnExpr,
    RankBySparseKnn,
    RankByText,
    RankByAttribute,
    RankByAttributes,
]
RerankBy = Union[Tuple[Literal["RRF"]], Tuple[Literal["RRF"], RrfParams]]
