#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

apigen_image=ghcr.io/turbopuffer/turbopuffer-apigen:e932946cf468628299aa55c51a8e69f9cffc1d8e

apigen() {
    if [[ "$TURBOPUFFER_DEV_APIGEN" ]]; then
        cargo run --manifest-path=../turbopuffer-apigen/Cargo.toml "$@"
    else
        docker run -v "$(pwd):/work" "$apigen_image" "$@"
    fi
}

echo "==> Generating code"
apigen python > src/turbopuffer/types/custom.py
