name: Release Please
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    if: github.repository == 'turbopuffer/turbopuffer-python'
    runs-on: ubuntu-latest

    steps:
      - name: Mint release token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.SDK_RELEASER_APP_ID }}
          private-key: ${{ secrets.SDK_RELEASER_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
